# -*- coding: utf-8 -*-
"""Personal Budget Tracker.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_br_zIxj0XQjJc3khqyl4EjzBEMsABX-
"""

#Python Journal Project
# PROGRAM: The Budget Tracker Program
# DATE: 5/July/2023


# Description:
# The problem I am planning to solve is to develop a personal budget tracker program.
# The program will help individuals track their income and expenses, allowing them to manage their finances effectively.

# Step 1: Input income
income = {}
income_total = 0

print("Enter your income sources:")
income_count = int(input("Number of income sources: "))

# Prompt user to input income sources and their corresponding amounts
for i in range(income_count):
    source = input("Income source: ")
    amount = float(input("Amount: "))
    income[source] = amount
    income_total += amount

# Step 2: Input expenses
expenses = {}
expenses_total = 0

print("Enter your expenses:")
expense_count = int(input("Number of expense categories: "))

# Prompt user to input expense categories and their corresponding amounts
for i in range(expense_count):
    category = input("Expense category: ")
    amount = float(input("Amount: "))
    expenses[category] = amount
    expenses_total += amount

# Step 3: Calculate savings
savings = income_total - expenses_total

# Step 4: Budget analysis
if expenses_total > income_total:
    budget_analysis = "Your expenses exceed your income. Consider adjusting your spending habits."
else:
    budget_analysis = "Your expenses are within your income. Good job!"

# Step 5: Display results
print("Total Income:", income_total)
print("Total Expenses:", expenses_total)
print("Savings:", savings)
print("Budget Analysis:", budget_analysis)

#THE END